# Usa una imagen base de NGINX, ligera y rápida
FROM nginx:alpine

# Elimina la página por defecto de NGINX
RUN rm -rf /usr/share/nginx/html/*

# Copia tus archivos HTML al directorio público de NGINX
COPY . /usr/share/nginx/html

# Expón el puerto 80
EXPOSE 80

# Inicia NGINX en modo foreground
CMD ["nginx", "-g", "daemon off;"]
